### ISSUE TITLE
Type hints in PyCharm

### ISSUE THREAD

**Issue by wpk-** [intellimath/recordclass#1]
Thanks for the package, works wonders.
I found a slight difference with `NamedTuple`. When I have this class:

```
class T(NamedTuple):
    a: int = 0
    b: int = 1
    c: str = 'c'
```

Then when I type `x = T(` PyCharm will show a tooltip with the three arguments `a`, `b` and `c` to help me fill in the arguments, a feature I love. However, when the parent class is `RecordClass` the tooltip shows `typename`, `fields` and `**kwargs`.

Also, the parenthesized part in `x = T(1, 2, 'd')` is marked as warning saying "Unexpected argument(s)".

**Comment by intellimath** [comment]
I don't use PyCharm and can't reproduce this issue. But I make change in order to make the code of typing.NamedTuple and recordclass.typing.RecordClass almost identical. Can you test the latest code from MAIN bitbucket repository - bitbucket.org/intellimath/recordclass ?

**Comment by intellimath** [comment]
This can't be resolve in recordclass side.
