### ISSUE TITLE
Wheels not being distributed on PyPi

### ISSUE THREAD

**Issue by hulsed** [intellimath/recordclass#10]
One thing I've noticed is that wheels (.whl files) stopped being published to Python around recordclass version 0.22--instead only tar.gz files are being published. Unfortunately, this means that the external user has to install MS Studio Build Tools to build recordclass for their machine. If these wheel files could continue to be published, that would be helpful to the user, who may not want (or be able) to install these build tools.

Desired: https://pypi.org/project/recordclass/0.21/#files
Current: https://pypi.org/project/recordclass/0.22.1/#files

**Comment by intellimath** [comment]
appveyor stopped building my project, and wheel for windows was building appveyor. I am considering the possibility of creating wheels based on the github infrastructure.

**Comment by intellimath** [comment]
Wheels for windows was uploaded to PyPI.
