### ISSUE TITLE
Missing git version tags

### ISSUE THREAD

**Issue by kloczek** [intellimath/recordclass#3]
Is it possible to add at least least version git tag? 🤔

**Comment by intellimath** [comment]
I just added version tag 0.21.1

**Comment by kloczek** [comment]
Just yet another small thing .. is it possible to start making github releases?🤔

On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by kloczek** [comment]
And thank you 👍 😄

**Comment by intellimath** [comment]
Thank you. I will try to start making releases.
----------------------
*Best regards,*

*Zaur Shibzukhov*




вт, 28 нояб. 2023 г. в 20:33, Tomasz Kłoczko ***@***.***>:

**Comment by intellimath** [comment]
0.21.1 release is piblished.

**Comment by intellimath** [comment]
Done.
-----------------------
С уважением,
З.М. Шибзухов


вт, 28 нояб. 2023 г. в 21:01, Zaur Shibzukhov ***@***.***>:

**Comment by intellimath** [comment]
It's look like the issue is resolved.

**Comment by intellimath** [comment]
Done

**Comment by kloczek** [comment]
I really appreciate what you've done.
Thank you very much 👍 😄
